keys:
  - &desktop age1qr4pjxx6zyu77dc0plja5p8gve229cq3kyany70x3fjtuwgtfv3qza68x7
  - &laptop age18yeuyy6s0s4mdsmyah8vgy58detqaqwawcpzxmtyqkm5rtjr6phsecpue4

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *desktop
          - *laptop
