personalHashedPassword: ENC[AES256_GCM,data:JO2JMRjyGeCb18vcqBgqEGfrQwrnVtSwBhUD68Rx5yGOmxy7i1uyaDGRz4QkcTTRKfL/08C7NIQ30i6UIdL+yZkgF/l7JtJ3sg==,iv:bGjmnh5wO6Egyna0vUAcxp79dsuIUqmvfb+4iq+pGys=,tag:AkvPfeZUr6UZuUQPgUWIgQ==,type:str]
sops:
    age:
        - recipient: age1qr4pjxx6zyu77dc0plja5p8gve229cq3kyany70x3fjtuwgtfv3qza68x7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSzNiYlNoNWFlWjV6UTBW
            YlFyVEh0eUtCNEl6OFliNE1QVDBBV2VWN0FJCmVOcnFHdzhWYTJReWk2VkRTaXFL
            dUNvMEFQV1JhYkgrWTlPRmVlSkRqSVkKLS0tIFU4Zms0NUUrRjFaRXBURmdxcG42
            V2hhSEdDV2hHSVIrQTZCbmhpZm9tYmcKENnLJo5rxOaaN/5pOfHWQQqjYsJN8/iR
            U17rMATLWH6goY3W8AZUSVwR6JtZ+EWI6RIszlISQAn8bNx6QUsPSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18yeuyy6s0s4mdsmyah8vgy58detqaqwawcpzxmtyqkm5rtjr6phsecpue4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNm16Mk9KblFWYm1HT2Jx
            RDFaVXp3SFZTZ1JkaEwzbTJCejZJcXBHakRNCjE0RFJYSmQ1V0hBMVNhOThLYnlr
            b2FaTWY0Zmp1YzJNc2hnUm9DdDhKTE0KLS0tIGc1ZVlDNFlMQnFwcEN3V3hzQ2F1
            SjVteU54ak16d2Nmd1FHdFViZktDRTAK4QzDuEV125W/ITYDL+wGXe+xRwmbkkC0
            iOKgaBzE46/f66oWz/jnC2jUR+SitRBOVDaBq3/j5xxRwA27pwDuYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u0y37apcpmhz7puqrhx0jyerucy0u7gf6fc6dh6jrmwprct29djskzef3t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUCtLczJMb3c0bk45VjBy
            UHJQVDN0ck9EcU9HSjE1eHF3THlEMm55U1RnCi9FTmRGQS8rd3pkZ1E2WUpVYXBo
            NzdBL2xpQlZTci9jVEhjdDJVdU5DSzgKLS0tIDFEcWVubkFNRVI2RjJ4NGlJaUp2
            U3ZJS1JKWFZpTHRBU1VIZnBqVjk2bUUK334qRkiRdw3azwJo1KIOqvcFMMv4Gkqq
            1TsQHR1R5ZgxurPFkh+babFEu7j9f7FbiN25zBYuaq7KWjU87NvlIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T07:08:14Z"
    mac: ENC[AES256_GCM,data:tRPXcs1VDkwrha6oKqYHwkg/DwOez0cVHhN6eoALZH+Kx+2sBR8UQhhHgIs2pYkbkGymoO0mnzMUMlvcu66wff6RwUmGFRLpLpkVDKhK7A+wC5gZMD8VMOOMxIwU55b00kTTAFyCywh8yjMcjfXoxQgRBXiXRE8XMLEj2fEKHXg=,iv:jP1oQH5usdcM4yKbHL6lCReJRKaY+UL99hU1xLmayFE=,tag:OIzf/KmPEcnHW5cpLeoiZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
